from textwrap import dedent
from phi.assistant import Assistant
from phi.tools.python import PythonTools
import streamlit as st
from phi.llm.openai import OpenAIChat
import os

st.title("AI agent who designs AI assistants")
st.caption("Agent Agent")

# Get OpenAI API key from user
os.environ["OPENAI_API_KEY"] = "---"

if True:
    engineer = Assistant(
        name="AI Engineer",
        role="Defines the structure of and creates an Assistant from the phidata python package that will address the user input. Then responds to the user with an answer to the input based on the assistant.",
        llm=OpenAIChat(model="gpt-4o"),
        description=dedent(
            """\
        You are a world-class AI engineer that builds frameworks to define phidata Assistants that you interact with.
        Your AI assistants are designed to optimally address and respond to the various types of user input given to you.
        You then take what the assistant generates and appropriately respond back to the user.
        """
        ),
        instructions=[
            "Given the user input, design a framework for a phidata AI assistant who is specifically designed to perform the appropriate tasks to address the inquiry.",
            "The framework should include the role, description, and intructions to follow for the assistant that will best address the user input.",
            "If you're unsure about what the user is referring to, just make your best guess. DO NOT ask follow-up questions."
            "Ensure the phi assistant is well-structured, informative, and engaging.",
            "Define the assistant; utilize the OpenAIChat llm interface from the phidata package and indicate gpt-4o as the model when building the Assistant().",
            "Convert the user input into a question prompt that the assistant can best address given your design",
            "Run the Assistant and print it's response to the question.",
            "Then provide an answer to the user based on the results generated by your assistant.",
            "Only respond to the user with the answer, DO NOT respond with any of the designing you perform.",
            "Remember: the quality of the AI phidata assistant is important.",
            "Focus on clarity, conciseness, coherence, and overall quality."
        ],
        tools=[PythonTools(pip_install=True,run_code=True)],
        add_datetime_to_instructions=True,
        add_chat_history_to_prompt=True,
        num_history_messages=3,
    )


question = st.text_input("Interact with AI")

if st.button("Generate Response"):
    with st.spinner("Processing..."):
        response = engineer.run(f"User input: \'{question}\'", stream=True)
        st.write(response)